
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: vegetable
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: food_count
        description: 'number of veg type food'

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: vegetable
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: food_count
        description: 'number of veg type food'